apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: event-backend
  template:
    metadata:
      labels:
        app: event-backend
    spec:
      containers:
        - name: event-backend
          image: event-backend:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql-service:3306/eventsdb
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_DATASOURCE_PASSWORD
              value:
---
apiVersion: v1
kind: Service
metadata:
  name: event-backend-service
spec:
  selector:
    app: event-backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
